package genxsolution.vms.vmsbackend.maintenance_management.maintenance_record.repository;
import genxsolution.vms.vmsbackend.maintenance_management.maintenance_record.dto.MaintenanceRecordUpsertRequest; import genxsolution.vms.vmsbackend.maintenance_management.maintenance_record.model.MaintenanceRecord; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Repository; import java.sql.*; import java.util.*;
@Repository public class MaintenanceRecordRepository { private final JdbcTemplate jdbcTemplate; public MaintenanceRecordRepository(JdbcTemplate jdbcTemplate){this.jdbcTemplate=jdbcTemplate;}
public List<MaintenanceRecord> findAll(UUID companyId){ String sql="SELECT maintenance_id, company_id, company_code, vehicle_id, schedule_id, breakdown_id, standard_id, start_time, end_time, odometer_km, engine_hours, work_performed, parts_used, lubricants_used, labor_cost, parts_cost, lubricants_cost, other_cost, total_cost, next_service_date, next_service_odometer_km, status_id, created_at, created_by, approved_by, approved_at FROM maintenance_record "+(companyId==null?"":"WHERE company_id = ? ")+"ORDER BY created_at DESC"; return companyId==null?jdbcTemplate.query(sql,this::mapRow):jdbcTemplate.query(sql,this::mapRow,companyId); }
public Optional<MaintenanceRecord> findById(UUID id){ return jdbcTemplate.query("SELECT maintenance_id, company_id, company_code, vehicle_id, schedule_id, breakdown_id, standard_id, start_time, end_time, odometer_km, engine_hours, work_performed, parts_used, lubricants_used, labor_cost, parts_cost, lubricants_cost, other_cost, total_cost, next_service_date, next_service_odometer_km, status_id, created_at, created_by, approved_by, approved_at FROM maintenance_record WHERE maintenance_id = ?", this::mapRow, id).stream().findFirst(); }
public MaintenanceRecord create(MaintenanceRecordUpsertRequest r){ String sql="""
INSERT INTO maintenance_record (company_id, company_code, vehicle_id, schedule_id, breakdown_id, standard_id, start_time, end_time, odometer_km, engine_hours, work_performed, parts_used, lubricants_used, labor_cost, parts_cost, lubricants_cost, other_cost, total_cost, next_service_date, next_service_odometer_km, status_id, created_by, approved_by, approved_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?::jsonb, ?::jsonb, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING maintenance_id, company_id, company_code, vehicle_id, schedule_id, breakdown_id, standard_id, start_time, end_time, odometer_km, engine_hours, work_performed, parts_used, lubricants_used, labor_cost, parts_cost, lubricants_cost, other_cost, total_cost, next_service_date, next_service_odometer_km, status_id, created_at, created_by, approved_by, approved_at
"""; return jdbcTemplate.queryForObject(sql,this::mapRow,r.companyId(),r.companyCode(),r.vehicleId(),r.scheduleId(),r.breakdownId(),r.standardId(),r.startTime(),r.endTime(),r.odometerKm(),r.engineHours(),r.workPerformed(),r.partsUsed(),r.lubricantsUsed(),r.laborCost(),r.partsCost(),r.lubricantsCost(),r.otherCost(),r.totalCost(),r.nextServiceDate(),r.nextServiceOdometerKm(),r.statusId(),r.createdBy(),r.approvedBy(),r.approvedAt()); }
public Optional<MaintenanceRecord> update(UUID id,MaintenanceRecordUpsertRequest r){ String sql="""
UPDATE maintenance_record SET company_id = COALESCE(?, company_id), company_code = COALESCE(?, company_code), vehicle_id = COALESCE(?, vehicle_id), schedule_id = COALESCE(?, schedule_id), breakdown_id = COALESCE(?, breakdown_id), standard_id = COALESCE(?, standard_id), start_time = COALESCE(?, start_time), end_time = COALESCE(?, end_time), odometer_km = COALESCE(?, odometer_km), engine_hours = COALESCE(?, engine_hours), work_performed = COALESCE(?, work_performed), parts_used = COALESCE(?::jsonb, parts_used), lubricants_used = COALESCE(?::jsonb, lubricants_used), labor_cost = COALESCE(?, labor_cost), parts_cost = COALESCE(?, parts_cost), lubricants_cost = COALESCE(?, lubricants_cost), other_cost = COALESCE(?, other_cost), total_cost = COALESCE(?, total_cost), next_service_date = COALESCE(?, next_service_date), next_service_odometer_km = COALESCE(?, next_service_odometer_km), status_id = COALESCE(?, status_id), created_by = COALESCE(?, created_by), approved_by = COALESCE(?, approved_by), approved_at = COALESCE(?, approved_at)
WHERE maintenance_id = ?
RETURNING maintenance_id, company_id, company_code, vehicle_id, schedule_id, breakdown_id, standard_id, start_time, end_time, odometer_km, engine_hours, work_performed, parts_used, lubricants_used, labor_cost, parts_cost, lubricants_cost, other_cost, total_cost, next_service_date, next_service_odometer_km, status_id, created_at, created_by, approved_by, approved_at
"""; return jdbcTemplate.query(sql,this::mapRow,r.companyId(),r.companyCode(),r.vehicleId(),r.scheduleId(),r.breakdownId(),r.standardId(),r.startTime(),r.endTime(),r.odometerKm(),r.engineHours(),r.workPerformed(),r.partsUsed(),r.lubricantsUsed(),r.laborCost(),r.partsCost(),r.lubricantsCost(),r.otherCost(),r.totalCost(),r.nextServiceDate(),r.nextServiceOdometerKm(),r.statusId(),r.createdBy(),r.approvedBy(),r.approvedAt(),id).stream().findFirst(); }
public boolean delete(UUID id){ return jdbcTemplate.update("DELETE FROM maintenance_record WHERE maintenance_id = ?", id)>0; }
private MaintenanceRecord mapRow(ResultSet rs,int n)throws SQLException{ Timestamp startTimeTs=rs.getTimestamp("start_time"); Timestamp endTimeTs=rs.getTimestamp("end_time"); java.sql.Date nextServiceDateDate=rs.getDate("next_service_date"); Timestamp createdAtTs=rs.getTimestamp("created_at"); Timestamp approvedAtTs=rs.getTimestamp("approved_at"); return new MaintenanceRecord(rs.getObject("maintenance_id",UUID.class),rs.getObject("company_id",UUID.class),rs.getString("company_code"),rs.getObject("vehicle_id",UUID.class),rs.getObject("schedule_id",UUID.class),rs.getObject("breakdown_id",UUID.class),rs.getObject("standard_id",UUID.class),startTimeTs==null?null:startTimeTs.toInstant(),endTimeTs==null?null:endTimeTs.toInstant(),rs.getBigDecimal("odometer_km"),rs.getBigDecimal("engine_hours"),rs.getString("work_performed"),rs.getString("parts_used"),rs.getString("lubricants_used"),rs.getBigDecimal("labor_cost"),rs.getBigDecimal("parts_cost"),rs.getBigDecimal("lubricants_cost"),rs.getBigDecimal("other_cost"),rs.getBigDecimal("total_cost"),nextServiceDateDate==null?null:nextServiceDateDate.toLocalDate(),rs.getBigDecimal("next_service_odometer_km"),rs.getObject("status_id",Integer.class),createdAtTs==null?null:createdAtTs.toInstant(),rs.getObject("created_by",UUID.class),rs.getObject("approved_by",UUID.class),approvedAtTs==null?null:approvedAtTs.toInstant()); }
}
