services:
  - type: web
    name: vms-backend
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: SPRING_DATA_REDIS_HOST
        sync: false
      - key: SPRING_DATA_REDIS_PORT
        value: "6379"
      - key: SPRING_DATA_REDIS_PASSWORD
        sync: false
      - key: VMS_SUPER_ADMIN_ENABLED
        value: "false"
