package genxsolution.vms.vmsbackend.maintenance_management.maintenance_standard.repository;
import genxsolution.vms.vmsbackend.maintenance_management.maintenance_standard.dto.MaintenanceStandardUpsertRequest; import genxsolution.vms.vmsbackend.maintenance_management.maintenance_standard.model.MaintenanceStandard; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Repository; import java.sql.*; import java.util.*;
@Repository public class MaintenanceStandardRepository { private final JdbcTemplate jdbcTemplate; public MaintenanceStandardRepository(JdbcTemplate jdbcTemplate){this.jdbcTemplate=jdbcTemplate;}
public List<MaintenanceStandard> findAll(UUID companyId){ String sql="SELECT standard_id, company_id, company_code, type_id, strategy_id, standard_code, name, category_id, interval_km, interval_months, interval_engine_hours, checklist, is_active FROM maintenance_standard "+(companyId==null?"":"WHERE company_id = ? ")+"ORDER BY standard_id DESC"; return companyId==null?jdbcTemplate.query(sql,this::mapRow):jdbcTemplate.query(sql,this::mapRow,companyId); }
public Optional<MaintenanceStandard> findById(UUID id){ return jdbcTemplate.query("SELECT standard_id, company_id, company_code, type_id, strategy_id, standard_code, name, category_id, interval_km, interval_months, interval_engine_hours, checklist, is_active FROM maintenance_standard WHERE standard_id = ?", this::mapRow, id).stream().findFirst(); }
public MaintenanceStandard create(MaintenanceStandardUpsertRequest r){ String sql="""
INSERT INTO maintenance_standard (company_id, company_code, type_id, strategy_id, standard_code, name, category_id, interval_km, interval_months, interval_engine_hours, checklist, is_active)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?::jsonb, ?)
RETURNING standard_id, company_id, company_code, type_id, strategy_id, standard_code, name, category_id, interval_km, interval_months, interval_engine_hours, checklist, is_active
"""; return jdbcTemplate.queryForObject(sql,this::mapRow,r.companyId(),r.companyCode(),r.typeId(),r.strategyId(),r.standardCode(),r.name(),r.categoryId(),r.intervalKm(),r.intervalMonths(),r.intervalEngineHours(),r.checklist(),r.isActive()); }
public Optional<MaintenanceStandard> update(UUID id,MaintenanceStandardUpsertRequest r){ String sql="""
UPDATE maintenance_standard SET company_id = COALESCE(?, company_id), company_code = COALESCE(?, company_code), type_id = COALESCE(?, type_id), strategy_id = COALESCE(?, strategy_id), standard_code = COALESCE(?, standard_code), name = COALESCE(?, name), category_id = COALESCE(?, category_id), interval_km = COALESCE(?, interval_km), interval_months = COALESCE(?, interval_months), interval_engine_hours = COALESCE(?, interval_engine_hours), checklist = COALESCE(?::jsonb, checklist), is_active = COALESCE(?, is_active)
WHERE standard_id = ?
RETURNING standard_id, company_id, company_code, type_id, strategy_id, standard_code, name, category_id, interval_km, interval_months, interval_engine_hours, checklist, is_active
"""; return jdbcTemplate.query(sql,this::mapRow,r.companyId(),r.companyCode(),r.typeId(),r.strategyId(),r.standardCode(),r.name(),r.categoryId(),r.intervalKm(),r.intervalMonths(),r.intervalEngineHours(),r.checklist(),r.isActive(),id).stream().findFirst(); }
public boolean delete(UUID id){ return jdbcTemplate.update("DELETE FROM maintenance_standard WHERE standard_id = ?", id)>0; }
private MaintenanceStandard mapRow(ResultSet rs,int n)throws SQLException{  return new MaintenanceStandard(rs.getObject("standard_id",UUID.class),rs.getObject("company_id",UUID.class),rs.getString("company_code"),rs.getObject("type_id",UUID.class),rs.getObject("strategy_id",UUID.class),rs.getString("standard_code"),rs.getString("name"),rs.getObject("category_id",Integer.class),rs.getObject("interval_km",Integer.class),rs.getObject("interval_months",Integer.class),rs.getObject("interval_engine_hours",Integer.class),rs.getString("checklist"),rs.getObject("is_active",Boolean.class)); }
}
