package genxsolution.vms.vmsbackend.maintenance_management.maintenance_assignment.repository;
import genxsolution.vms.vmsbackend.maintenance_management.maintenance_assignment.dto.MaintenanceAssignmentUpsertRequest; import genxsolution.vms.vmsbackend.maintenance_management.maintenance_assignment.model.MaintenanceAssignment; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Repository; import java.sql.*; import java.util.*;
@Repository public class MaintenanceAssignmentRepository { private final JdbcTemplate jdbcTemplate; public MaintenanceAssignmentRepository(JdbcTemplate jdbcTemplate){this.jdbcTemplate=jdbcTemplate;}
public List<MaintenanceAssignment> findAll(UUID companyId){ String sql="SELECT assignment_id, company_id, company_code, breakdown_id, maintenance_id, technician_id, assigned_at, started_at, completed_at, status_id, notes FROM maintenance_assignment "+(companyId==null?"":"WHERE company_id = ? ")+"ORDER BY assigned_at DESC"; return companyId==null?jdbcTemplate.query(sql,this::mapRow):jdbcTemplate.query(sql,this::mapRow,companyId); }
public Optional<MaintenanceAssignment> findById(UUID id){ return jdbcTemplate.query("SELECT assignment_id, company_id, company_code, breakdown_id, maintenance_id, technician_id, assigned_at, started_at, completed_at, status_id, notes FROM maintenance_assignment WHERE assignment_id = ?", this::mapRow, id).stream().findFirst(); }
public MaintenanceAssignment create(MaintenanceAssignmentUpsertRequest r){ String sql="""
INSERT INTO maintenance_assignment (company_id, company_code, breakdown_id, maintenance_id, technician_id, assigned_at, started_at, completed_at, status_id, notes)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING assignment_id, company_id, company_code, breakdown_id, maintenance_id, technician_id, assigned_at, started_at, completed_at, status_id, notes
"""; return jdbcTemplate.queryForObject(sql,this::mapRow,r.companyId(),r.companyCode(),r.breakdownId(),r.maintenanceId(),r.technicianId(),r.assignedAt(),r.startedAt(),r.completedAt(),r.statusId(),r.notes()); }
public Optional<MaintenanceAssignment> update(UUID id,MaintenanceAssignmentUpsertRequest r){ String sql="""
UPDATE maintenance_assignment SET company_id = COALESCE(?, company_id), company_code = COALESCE(?, company_code), breakdown_id = COALESCE(?, breakdown_id), maintenance_id = COALESCE(?, maintenance_id), technician_id = COALESCE(?, technician_id), assigned_at = COALESCE(?, assigned_at), started_at = COALESCE(?, started_at), completed_at = COALESCE(?, completed_at), status_id = COALESCE(?, status_id), notes = COALESCE(?, notes)
WHERE assignment_id = ?
RETURNING assignment_id, company_id, company_code, breakdown_id, maintenance_id, technician_id, assigned_at, started_at, completed_at, status_id, notes
"""; return jdbcTemplate.query(sql,this::mapRow,r.companyId(),r.companyCode(),r.breakdownId(),r.maintenanceId(),r.technicianId(),r.assignedAt(),r.startedAt(),r.completedAt(),r.statusId(),r.notes(),id).stream().findFirst(); }
public boolean delete(UUID id){ return jdbcTemplate.update("DELETE FROM maintenance_assignment WHERE assignment_id = ?", id)>0; }
private MaintenanceAssignment mapRow(ResultSet rs,int n)throws SQLException{ Timestamp assignedAtTs=rs.getTimestamp("assigned_at"); Timestamp startedAtTs=rs.getTimestamp("started_at"); Timestamp completedAtTs=rs.getTimestamp("completed_at"); return new MaintenanceAssignment(rs.getObject("assignment_id",UUID.class),rs.getObject("company_id",UUID.class),rs.getString("company_code"),rs.getObject("breakdown_id",UUID.class),rs.getObject("maintenance_id",UUID.class),rs.getObject("technician_id",UUID.class),assignedAtTs==null?null:assignedAtTs.toInstant(),startedAtTs==null?null:startedAtTs.toInstant(),completedAtTs==null?null:completedAtTs.toInstant(),rs.getObject("status_id",Integer.class),rs.getString("notes")); }
}
