package genxsolution.vms.vmsbackend.maintenance_management.maintenance_program_template.repository;
import genxsolution.vms.vmsbackend.maintenance_management.maintenance_program_template.dto.MaintenanceProgramTemplateUpsertRequest; import genxsolution.vms.vmsbackend.maintenance_management.maintenance_program_template.model.MaintenanceProgramTemplate; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Repository; import java.sql.*; import java.util.*;
@Repository public class MaintenanceProgramTemplateRepository { private final JdbcTemplate jdbcTemplate; public MaintenanceProgramTemplateRepository(JdbcTemplate jdbcTemplate){this.jdbcTemplate=jdbcTemplate;}
public List<MaintenanceProgramTemplate> findAll(UUID companyId){ String sql="SELECT template_id, company_id, company_code, program_name, vehicle_type_id, program_type, interval_type, interval_value, checklist_template, estimated_duration_hours, estimated_cost, is_active FROM maintenance_program_template "+(companyId==null?"":"WHERE company_id = ? ")+"ORDER BY template_id DESC"; return companyId==null?jdbcTemplate.query(sql,this::mapRow):jdbcTemplate.query(sql,this::mapRow,companyId); }
public Optional<MaintenanceProgramTemplate> findById(UUID id){ return jdbcTemplate.query("SELECT template_id, company_id, company_code, program_name, vehicle_type_id, program_type, interval_type, interval_value, checklist_template, estimated_duration_hours, estimated_cost, is_active FROM maintenance_program_template WHERE template_id = ?", this::mapRow, id).stream().findFirst(); }
public MaintenanceProgramTemplate create(MaintenanceProgramTemplateUpsertRequest r){ String sql="""
INSERT INTO maintenance_program_template (company_id, company_code, program_name, vehicle_type_id, program_type, interval_type, interval_value, checklist_template, estimated_duration_hours, estimated_cost, is_active)
VALUES (?, ?, ?, ?, ?, ?, ?, ?::jsonb, ?, ?, ?)
RETURNING template_id, company_id, company_code, program_name, vehicle_type_id, program_type, interval_type, interval_value, checklist_template, estimated_duration_hours, estimated_cost, is_active
"""; return jdbcTemplate.queryForObject(sql,this::mapRow,r.companyId(),r.companyCode(),r.programName(),r.vehicleTypeId(),r.programType(),r.intervalType(),r.intervalValue(),r.checklistTemplate(),r.estimatedDurationHours(),r.estimatedCost(),r.isActive()); }
public Optional<MaintenanceProgramTemplate> update(UUID id,MaintenanceProgramTemplateUpsertRequest r){ String sql="""
UPDATE maintenance_program_template SET company_id = COALESCE(?, company_id), company_code = COALESCE(?, company_code), program_name = COALESCE(?, program_name), vehicle_type_id = COALESCE(?, vehicle_type_id), program_type = COALESCE(?, program_type), interval_type = COALESCE(?, interval_type), interval_value = COALESCE(?, interval_value), checklist_template = COALESCE(?::jsonb, checklist_template), estimated_duration_hours = COALESCE(?, estimated_duration_hours), estimated_cost = COALESCE(?, estimated_cost), is_active = COALESCE(?, is_active)
WHERE template_id = ?
RETURNING template_id, company_id, company_code, program_name, vehicle_type_id, program_type, interval_type, interval_value, checklist_template, estimated_duration_hours, estimated_cost, is_active
"""; return jdbcTemplate.query(sql,this::mapRow,r.companyId(),r.companyCode(),r.programName(),r.vehicleTypeId(),r.programType(),r.intervalType(),r.intervalValue(),r.checklistTemplate(),r.estimatedDurationHours(),r.estimatedCost(),r.isActive(),id).stream().findFirst(); }
public boolean delete(UUID id){ return jdbcTemplate.update("DELETE FROM maintenance_program_template WHERE template_id = ?", id)>0; }
private MaintenanceProgramTemplate mapRow(ResultSet rs,int n)throws SQLException{  return new MaintenanceProgramTemplate(rs.getObject("template_id",UUID.class),rs.getObject("company_id",UUID.class),rs.getString("company_code"),rs.getString("program_name"),rs.getObject("vehicle_type_id",UUID.class),rs.getString("program_type"),rs.getString("interval_type"),rs.getObject("interval_value",Integer.class),rs.getString("checklist_template"),rs.getBigDecimal("estimated_duration_hours"),rs.getBigDecimal("estimated_cost"),rs.getObject("is_active",Boolean.class)); }
}
