package genxsolution.vms.vmsbackend.maintenance_management.breakdown_record.repository;
import genxsolution.vms.vmsbackend.maintenance_management.breakdown_record.dto.BreakdownRecordUpsertRequest; import genxsolution.vms.vmsbackend.maintenance_management.breakdown_record.model.BreakdownRecord; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Repository; import java.sql.*; import java.util.*;
@Repository public class BreakdownRecordRepository { private final JdbcTemplate jdbcTemplate; public BreakdownRecordRepository(JdbcTemplate jdbcTemplate){this.jdbcTemplate=jdbcTemplate;}
public List<BreakdownRecord> findAll(UUID companyId){ String sql="SELECT breakdown_id, company_id, company_code, vehicle_id, driver_id, project_id, breakdown_at, location, odometer_km, breakdown_type_id, severity_id, description, repair_category_id, repair_location_id, status_id, created_at FROM breakdown_record "+(companyId==null?"":"WHERE company_id = ? ")+"ORDER BY created_at DESC"; return companyId==null?jdbcTemplate.query(sql,this::mapRow):jdbcTemplate.query(sql,this::mapRow,companyId); }
public Optional<BreakdownRecord> findById(UUID id){ return jdbcTemplate.query("SELECT breakdown_id, company_id, company_code, vehicle_id, driver_id, project_id, breakdown_at, location, odometer_km, breakdown_type_id, severity_id, description, repair_category_id, repair_location_id, status_id, created_at FROM breakdown_record WHERE breakdown_id = ?", this::mapRow, id).stream().findFirst(); }
public BreakdownRecord create(BreakdownRecordUpsertRequest r){ String sql="""
INSERT INTO breakdown_record (company_id, company_code, vehicle_id, driver_id, project_id, breakdown_at, location, odometer_km, breakdown_type_id, severity_id, description, repair_category_id, repair_location_id, status_id)
VALUES (?, ?, ?, ?, ?, ?, ?::point, ?, ?, ?, ?, ?, ?, ?)
RETURNING breakdown_id, company_id, company_code, vehicle_id, driver_id, project_id, breakdown_at, location, odometer_km, breakdown_type_id, severity_id, description, repair_category_id, repair_location_id, status_id, created_at
"""; return jdbcTemplate.queryForObject(sql,this::mapRow,r.companyId(),r.companyCode(),r.vehicleId(),r.driverId(),r.projectId(),r.breakdownAt(),r.location(),r.odometerKm(),r.breakdownTypeId(),r.severityId(),r.description(),r.repairCategoryId(),r.repairLocationId(),r.statusId()); }
public Optional<BreakdownRecord> update(UUID id,BreakdownRecordUpsertRequest r){ String sql="""
UPDATE breakdown_record SET company_id = COALESCE(?, company_id), company_code = COALESCE(?, company_code), vehicle_id = COALESCE(?, vehicle_id), driver_id = COALESCE(?, driver_id), project_id = COALESCE(?, project_id), breakdown_at = COALESCE(?, breakdown_at), location = COALESCE(?::point, location), odometer_km = COALESCE(?, odometer_km), breakdown_type_id = COALESCE(?, breakdown_type_id), severity_id = COALESCE(?, severity_id), description = COALESCE(?, description), repair_category_id = COALESCE(?, repair_category_id), repair_location_id = COALESCE(?, repair_location_id), status_id = COALESCE(?, status_id)
WHERE breakdown_id = ?
RETURNING breakdown_id, company_id, company_code, vehicle_id, driver_id, project_id, breakdown_at, location, odometer_km, breakdown_type_id, severity_id, description, repair_category_id, repair_location_id, status_id, created_at
"""; return jdbcTemplate.query(sql,this::mapRow,r.companyId(),r.companyCode(),r.vehicleId(),r.driverId(),r.projectId(),r.breakdownAt(),r.location(),r.odometerKm(),r.breakdownTypeId(),r.severityId(),r.description(),r.repairCategoryId(),r.repairLocationId(),r.statusId(),id).stream().findFirst(); }
public boolean delete(UUID id){ return jdbcTemplate.update("DELETE FROM breakdown_record WHERE breakdown_id = ?", id)>0; }
private BreakdownRecord mapRow(ResultSet rs,int n)throws SQLException{ Timestamp breakdownAtTs=rs.getTimestamp("breakdown_at"); Timestamp createdAtTs=rs.getTimestamp("created_at"); return new BreakdownRecord(rs.getObject("breakdown_id",UUID.class),rs.getObject("company_id",UUID.class),rs.getString("company_code"),rs.getObject("vehicle_id",UUID.class),rs.getObject("driver_id",UUID.class),rs.getObject("project_id",UUID.class),breakdownAtTs==null?null:breakdownAtTs.toInstant(),rs.getString("location"),rs.getBigDecimal("odometer_km"),rs.getObject("breakdown_type_id",Integer.class),rs.getObject("severity_id",Integer.class),rs.getString("description"),rs.getObject("repair_category_id",Integer.class),rs.getObject("repair_location_id",Integer.class),rs.getObject("status_id",Integer.class),createdAtTs==null?null:createdAtTs.toInstant()); }
}
