package genxsolution.vms.vmsbackend.maintenance_management.maintenance_plan.repository;
import genxsolution.vms.vmsbackend.maintenance_management.maintenance_plan.dto.MaintenancePlanUpsertRequest; import genxsolution.vms.vmsbackend.maintenance_management.maintenance_plan.model.MaintenancePlan; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Repository; import java.sql.*; import java.util.*;
@Repository public class MaintenancePlanRepository { private final JdbcTemplate jdbcTemplate; public MaintenancePlanRepository(JdbcTemplate jdbcTemplate){this.jdbcTemplate=jdbcTemplate;}
public List<MaintenancePlan> findAll(UUID companyId){ String sql="SELECT plan_id, company_id, company_code, vehicle_id, plan_name, plan_type_id, start_date, end_date, total_estimated_cost, status_id, created_by, created_at FROM maintenance_plan "+(companyId==null?"":"WHERE company_id = ? ")+"ORDER BY created_at DESC"; return companyId==null?jdbcTemplate.query(sql,this::mapRow):jdbcTemplate.query(sql,this::mapRow,companyId); }
public Optional<MaintenancePlan> findById(UUID id){ return jdbcTemplate.query("SELECT plan_id, company_id, company_code, vehicle_id, plan_name, plan_type_id, start_date, end_date, total_estimated_cost, status_id, created_by, created_at FROM maintenance_plan WHERE plan_id = ?", this::mapRow, id).stream().findFirst(); }
public MaintenancePlan create(MaintenancePlanUpsertRequest r){ String sql="""
INSERT INTO maintenance_plan (company_id, company_code, vehicle_id, plan_name, plan_type_id, start_date, end_date, total_estimated_cost, status_id, created_by)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING plan_id, company_id, company_code, vehicle_id, plan_name, plan_type_id, start_date, end_date, total_estimated_cost, status_id, created_by, created_at
"""; return jdbcTemplate.queryForObject(sql,this::mapRow,r.companyId(),r.companyCode(),r.vehicleId(),r.planName(),r.planTypeId(),r.startDate(),r.endDate(),r.totalEstimatedCost(),r.statusId(),r.createdBy()); }
public Optional<MaintenancePlan> update(UUID id,MaintenancePlanUpsertRequest r){ String sql="""
UPDATE maintenance_plan SET company_id = COALESCE(?, company_id), company_code = COALESCE(?, company_code), vehicle_id = COALESCE(?, vehicle_id), plan_name = COALESCE(?, plan_name), plan_type_id = COALESCE(?, plan_type_id), start_date = COALESCE(?, start_date), end_date = COALESCE(?, end_date), total_estimated_cost = COALESCE(?, total_estimated_cost), status_id = COALESCE(?, status_id), created_by = COALESCE(?, created_by)
WHERE plan_id = ?
RETURNING plan_id, company_id, company_code, vehicle_id, plan_name, plan_type_id, start_date, end_date, total_estimated_cost, status_id, created_by, created_at
"""; return jdbcTemplate.query(sql,this::mapRow,r.companyId(),r.companyCode(),r.vehicleId(),r.planName(),r.planTypeId(),r.startDate(),r.endDate(),r.totalEstimatedCost(),r.statusId(),r.createdBy(),id).stream().findFirst(); }
public boolean delete(UUID id){ return jdbcTemplate.update("DELETE FROM maintenance_plan WHERE plan_id = ?", id)>0; }
private MaintenancePlan mapRow(ResultSet rs,int n)throws SQLException{ java.sql.Date startDateDate=rs.getDate("start_date"); java.sql.Date endDateDate=rs.getDate("end_date"); Timestamp createdAtTs=rs.getTimestamp("created_at"); return new MaintenancePlan(rs.getObject("plan_id",UUID.class),rs.getObject("company_id",UUID.class),rs.getString("company_code"),rs.getObject("vehicle_id",UUID.class),rs.getString("plan_name"),rs.getObject("plan_type_id",Integer.class),startDateDate==null?null:startDateDate.toLocalDate(),endDateDate==null?null:endDateDate.toLocalDate(),rs.getBigDecimal("total_estimated_cost"),rs.getObject("status_id",Integer.class),rs.getObject("created_by",UUID.class),createdAtTs==null?null:createdAtTs.toInstant()); }
}
