package genxsolution.vms.vmsbackend.employee_hr_management.payroll.repository;
import genxsolution.vms.vmsbackend.employee_hr_management.payroll.dto.PayrollUpsertRequest; import genxsolution.vms.vmsbackend.employee_hr_management.payroll.model.Payroll; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Repository; import java.sql.*; import java.util.*;
@Repository public class PayrollRepository { private final JdbcTemplate jdbcTemplate; public PayrollRepository(JdbcTemplate jdbcTemplate){this.jdbcTemplate=jdbcTemplate;}
public List<Payroll> findAll(UUID companyId){ String sql="SELECT payroll_id, company_id, company_code, employee_id, payroll_month, payroll_year, basic_salary, overtime_hours, overtime_amount, ration_total, allowances_total, advance_deductions, other_deductions, net_salary, payment_date, payment_method_id, status_id, created_at FROM payroll "+(companyId==null?"":"WHERE company_id = ? ")+"ORDER BY payroll_year DESC, payroll_month DESC, created_at DESC"; return companyId==null?jdbcTemplate.query(sql,this::mapRow):jdbcTemplate.query(sql,this::mapRow,companyId);} 
public Optional<Payroll> findById(UUID id){ return jdbcTemplate.query("SELECT payroll_id, company_id, company_code, employee_id, payroll_month, payroll_year, basic_salary, overtime_hours, overtime_amount, ration_total, allowances_total, advance_deductions, other_deductions, net_salary, payment_date, payment_method_id, status_id, created_at FROM payroll WHERE payroll_id = ?", this::mapRow, id).stream().findFirst(); }
public Payroll create(PayrollUpsertRequest r){ String sql="""
INSERT INTO payroll (company_id, company_code, employee_id, payroll_month, payroll_year, basic_salary, overtime_hours, overtime_amount, ration_total, allowances_total, advance_deductions, other_deductions, net_salary, payment_date, payment_method_id, status_id)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING payroll_id, company_id, company_code, employee_id, payroll_month, payroll_year, basic_salary, overtime_hours, overtime_amount, ration_total, allowances_total, advance_deductions, other_deductions, net_salary, payment_date, payment_method_id, status_id, created_at
"""; return jdbcTemplate.queryForObject(sql,this::mapRow,r.companyId(),r.companyCode(),r.employeeId(),r.payrollMonth(),r.payrollYear(),r.basicSalary(),r.overtimeHours(),r.overtimeAmount(),r.rationTotal(),r.allowancesTotal(),r.advanceDeductions(),r.otherDeductions(),r.netSalary(),r.paymentDate(),r.paymentMethodId(),r.statusId()); }
public Optional<Payroll> update(UUID id,PayrollUpsertRequest r){ String sql="""
UPDATE payroll SET employee_id = COALESCE(?, employee_id), payroll_month = COALESCE(?, payroll_month), payroll_year = COALESCE(?, payroll_year), basic_salary = COALESCE(?, basic_salary), overtime_hours = COALESCE(?, overtime_hours), overtime_amount = COALESCE(?, overtime_amount), ration_total = COALESCE(?, ration_total), allowances_total = COALESCE(?, allowances_total), advance_deductions = COALESCE(?, advance_deductions), other_deductions = COALESCE(?, other_deductions), net_salary = COALESCE(?, net_salary), payment_date = COALESCE(?, payment_date), payment_method_id = COALESCE(?, payment_method_id), status_id = COALESCE(?, status_id)
WHERE payroll_id = ?
RETURNING payroll_id, company_id, company_code, employee_id, payroll_month, payroll_year, basic_salary, overtime_hours, overtime_amount, ration_total, allowances_total, advance_deductions, other_deductions, net_salary, payment_date, payment_method_id, status_id, created_at
"""; return jdbcTemplate.query(sql,this::mapRow,r.employeeId(),r.payrollMonth(),r.payrollYear(),r.basicSalary(),r.overtimeHours(),r.overtimeAmount(),r.rationTotal(),r.allowancesTotal(),r.advanceDeductions(),r.otherDeductions(),r.netSalary(),r.paymentDate(),r.paymentMethodId(),r.statusId(),id).stream().findFirst(); }
public boolean delete(UUID id){ return jdbcTemplate.update("DELETE FROM payroll WHERE payroll_id = ?", id)>0; }
private Payroll mapRow(ResultSet rs,int n)throws SQLException{ java.sql.Date p=rs.getDate("payment_date"); Timestamp c=rs.getTimestamp("created_at"); return new Payroll(rs.getObject("payroll_id",UUID.class),rs.getObject("company_id",UUID.class),rs.getString("company_code"),rs.getObject("employee_id",UUID.class),rs.getObject("payroll_month",Integer.class),rs.getObject("payroll_year",Integer.class),rs.getBigDecimal("basic_salary"),rs.getBigDecimal("overtime_hours"),rs.getBigDecimal("overtime_amount"),rs.getBigDecimal("ration_total"),rs.getBigDecimal("allowances_total"),rs.getBigDecimal("advance_deductions"),rs.getBigDecimal("other_deductions"),rs.getBigDecimal("net_salary"),p==null?null:p.toLocalDate(),rs.getObject("payment_method_id",Integer.class),rs.getObject("status_id",Integer.class),c==null?null:c.toInstant()); }
}
