package genxsolution.vms.vmsbackend.maintenance_management.vehicle_filter.repository;
import genxsolution.vms.vmsbackend.maintenance_management.vehicle_filter.dto.VehicleFilterUpsertRequest; import genxsolution.vms.vmsbackend.maintenance_management.vehicle_filter.model.VehicleFilter; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Repository; import java.sql.*; import java.util.*;
@Repository public class VehicleFilterRepository { private final JdbcTemplate jdbcTemplate; public VehicleFilterRepository(JdbcTemplate jdbcTemplate){this.jdbcTemplate=jdbcTemplate;}
public List<VehicleFilter> findAll(UUID companyId){ String sql="SELECT filter_id, company_id, company_code, vehicle_id, filter_type_id, serial_number, installed_date, installed_odometer_km, installed_engine_hours, recommended_replacement_km, recommended_replacement_hours, actual_replacement_date, actual_replacement_km, actual_replacement_hours, replacement_reason, status_id, created_at FROM vehicle_filter "+(companyId==null?"":"WHERE company_id = ? ")+"ORDER BY filter_id DESC"; return companyId==null?jdbcTemplate.query(sql,this::mapRow):jdbcTemplate.query(sql,this::mapRow,companyId); }
public Optional<VehicleFilter> findById(UUID id){ return jdbcTemplate.query("SELECT filter_id, company_id, company_code, vehicle_id, filter_type_id, serial_number, installed_date, installed_odometer_km, installed_engine_hours, recommended_replacement_km, recommended_replacement_hours, actual_replacement_date, actual_replacement_km, actual_replacement_hours, replacement_reason, status_id, created_at FROM vehicle_filter WHERE filter_id = ?", this::mapRow, id).stream().findFirst(); }
public VehicleFilter create(VehicleFilterUpsertRequest r){ String sql="""
INSERT INTO vehicle_filter (company_id, company_code, vehicle_id, filter_type_id, serial_number, installed_date, installed_odometer_km, installed_engine_hours, recommended_replacement_km, recommended_replacement_hours, actual_replacement_date, actual_replacement_km, actual_replacement_hours, replacement_reason, status_id)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING filter_id, company_id, company_code, vehicle_id, filter_type_id, serial_number, installed_date, installed_odometer_km, installed_engine_hours, recommended_replacement_km, recommended_replacement_hours, actual_replacement_date, actual_replacement_km, actual_replacement_hours, replacement_reason, status_id, created_at
"""; return jdbcTemplate.queryForObject(sql,this::mapRow,r.companyId(),r.companyCode(),r.vehicleId(),r.filterTypeId(),r.serialNumber(),r.installedDate(),r.installedOdometerKm(),r.installedEngineHours(),r.recommendedReplacementKm(),r.recommendedReplacementHours(),r.actualReplacementDate(),r.actualReplacementKm(),r.actualReplacementHours(),r.replacementReason(),r.statusId()); }
public Optional<VehicleFilter> update(UUID id,VehicleFilterUpsertRequest r){ String sql="""
UPDATE vehicle_filter SET company_id = COALESCE(?, company_id), company_code = COALESCE(?, company_code), vehicle_id = COALESCE(?, vehicle_id), filter_type_id = COALESCE(?, filter_type_id), serial_number = COALESCE(?, serial_number), installed_date = COALESCE(?, installed_date), installed_odometer_km = COALESCE(?, installed_odometer_km), installed_engine_hours = COALESCE(?, installed_engine_hours), recommended_replacement_km = COALESCE(?, recommended_replacement_km), recommended_replacement_hours = COALESCE(?, recommended_replacement_hours), actual_replacement_date = COALESCE(?, actual_replacement_date), actual_replacement_km = COALESCE(?, actual_replacement_km), actual_replacement_hours = COALESCE(?, actual_replacement_hours), replacement_reason = COALESCE(?, replacement_reason), status_id = COALESCE(?, status_id)
WHERE filter_id = ?
RETURNING filter_id, company_id, company_code, vehicle_id, filter_type_id, serial_number, installed_date, installed_odometer_km, installed_engine_hours, recommended_replacement_km, recommended_replacement_hours, actual_replacement_date, actual_replacement_km, actual_replacement_hours, replacement_reason, status_id, created_at
"""; return jdbcTemplate.query(sql,this::mapRow,r.companyId(),r.companyCode(),r.vehicleId(),r.filterTypeId(),r.serialNumber(),r.installedDate(),r.installedOdometerKm(),r.installedEngineHours(),r.recommendedReplacementKm(),r.recommendedReplacementHours(),r.actualReplacementDate(),r.actualReplacementKm(),r.actualReplacementHours(),r.replacementReason(),r.statusId(),id).stream().findFirst(); }
public boolean delete(UUID id){ return jdbcTemplate.update("DELETE FROM vehicle_filter WHERE filter_id = ?", id)>0; }
private VehicleFilter mapRow(ResultSet rs,int n)throws SQLException{ java.sql.Date installedDateDate=rs.getDate("installed_date"); java.sql.Date actualReplacementDateDate=rs.getDate("actual_replacement_date"); Timestamp createdAtTs=rs.getTimestamp("created_at"); return new VehicleFilter(rs.getObject("filter_id",UUID.class),rs.getObject("company_id",UUID.class),rs.getString("company_code"),rs.getObject("vehicle_id",UUID.class),rs.getObject("filter_type_id",UUID.class),rs.getString("serial_number"),installedDateDate==null?null:installedDateDate.toLocalDate(),rs.getBigDecimal("installed_odometer_km"),rs.getBigDecimal("installed_engine_hours"),rs.getBigDecimal("recommended_replacement_km"),rs.getBigDecimal("recommended_replacement_hours"),actualReplacementDateDate==null?null:actualReplacementDateDate.toLocalDate(),rs.getBigDecimal("actual_replacement_km"),rs.getBigDecimal("actual_replacement_hours"),rs.getString("replacement_reason"),rs.getObject("status_id",Integer.class),createdAtTs==null?null:createdAtTs.toInstant()); }
}
