package genxsolution.vms.vmsbackend.maintenance_management.maintenance_plan_item.repository;
import genxsolution.vms.vmsbackend.maintenance_management.maintenance_plan_item.dto.MaintenancePlanItemUpsertRequest; import genxsolution.vms.vmsbackend.maintenance_management.maintenance_plan_item.model.MaintenancePlanItem; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Repository; import java.sql.*; import java.util.*;
@Repository public class MaintenancePlanItemRepository { private final JdbcTemplate jdbcTemplate; public MaintenancePlanItemRepository(JdbcTemplate jdbcTemplate){this.jdbcTemplate=jdbcTemplate;}
public List<MaintenancePlanItem> findAll(UUID companyId){ String sql="SELECT plan_item_id, company_id, company_code, plan_id, standard_id, item_description, scheduled_date, estimated_cost, actual_cost, status_id, completed_date, notes, created_at FROM maintenance_plan_item "+(companyId==null?"":"WHERE company_id = ? ")+"ORDER BY created_at DESC"; return companyId==null?jdbcTemplate.query(sql,this::mapRow):jdbcTemplate.query(sql,this::mapRow,companyId); }
public Optional<MaintenancePlanItem> findById(UUID id){ return jdbcTemplate.query("SELECT plan_item_id, company_id, company_code, plan_id, standard_id, item_description, scheduled_date, estimated_cost, actual_cost, status_id, completed_date, notes, created_at FROM maintenance_plan_item WHERE plan_item_id = ?", this::mapRow, id).stream().findFirst(); }
public MaintenancePlanItem create(MaintenancePlanItemUpsertRequest r){ String sql="""
INSERT INTO maintenance_plan_item (company_id, company_code, plan_id, standard_id, item_description, scheduled_date, estimated_cost, actual_cost, status_id, completed_date, notes)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING plan_item_id, company_id, company_code, plan_id, standard_id, item_description, scheduled_date, estimated_cost, actual_cost, status_id, completed_date, notes, created_at
"""; return jdbcTemplate.queryForObject(sql,this::mapRow,r.companyId(),r.companyCode(),r.planId(),r.standardId(),r.itemDescription(),r.scheduledDate(),r.estimatedCost(),r.actualCost(),r.statusId(),r.completedDate(),r.notes()); }
public Optional<MaintenancePlanItem> update(UUID id,MaintenancePlanItemUpsertRequest r){ String sql="""
UPDATE maintenance_plan_item SET company_id = COALESCE(?, company_id), company_code = COALESCE(?, company_code), plan_id = COALESCE(?, plan_id), standard_id = COALESCE(?, standard_id), item_description = COALESCE(?, item_description), scheduled_date = COALESCE(?, scheduled_date), estimated_cost = COALESCE(?, estimated_cost), actual_cost = COALESCE(?, actual_cost), status_id = COALESCE(?, status_id), completed_date = COALESCE(?, completed_date), notes = COALESCE(?, notes)
WHERE plan_item_id = ?
RETURNING plan_item_id, company_id, company_code, plan_id, standard_id, item_description, scheduled_date, estimated_cost, actual_cost, status_id, completed_date, notes, created_at
"""; return jdbcTemplate.query(sql,this::mapRow,r.companyId(),r.companyCode(),r.planId(),r.standardId(),r.itemDescription(),r.scheduledDate(),r.estimatedCost(),r.actualCost(),r.statusId(),r.completedDate(),r.notes(),id).stream().findFirst(); }
public boolean delete(UUID id){ return jdbcTemplate.update("DELETE FROM maintenance_plan_item WHERE plan_item_id = ?", id)>0; }
private MaintenancePlanItem mapRow(ResultSet rs,int n)throws SQLException{ java.sql.Date scheduledDateDate=rs.getDate("scheduled_date"); java.sql.Date completedDateDate=rs.getDate("completed_date"); Timestamp createdAtTs=rs.getTimestamp("created_at"); return new MaintenancePlanItem(rs.getObject("plan_item_id",UUID.class),rs.getObject("company_id",UUID.class),rs.getString("company_code"),rs.getObject("plan_id",UUID.class),rs.getObject("standard_id",UUID.class),rs.getString("item_description"),scheduledDateDate==null?null:scheduledDateDate.toLocalDate(),rs.getBigDecimal("estimated_cost"),rs.getBigDecimal("actual_cost"),rs.getObject("status_id",Integer.class),completedDateDate==null?null:completedDateDate.toLocalDate(),rs.getString("notes"),createdAtTs==null?null:createdAtTs.toInstant()); }
}
