package genxsolution.vms.vmsbackend.vehicle_management.vehicle_daily_summary.repository;
import genxsolution.vms.vmsbackend.vehicle_management.vehicle_daily_summary.dto.VehicleDailySummaryUpsertRequest; import genxsolution.vms.vmsbackend.vehicle_management.vehicle_daily_summary.model.VehicleDailySummary; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Repository; import java.sql.*; import java.util.*;
@Repository public class VehicleDailySummaryRepository { private final JdbcTemplate jdbcTemplate; public VehicleDailySummaryRepository(JdbcTemplate jdbcTemplate){this.jdbcTemplate=jdbcTemplate;}
public List<VehicleDailySummary> findAll(UUID companyId){ String sql="SELECT summary_id, company_id, company_code, vehicle_id, summary_date, total_distance, total_engine_hours, total_fuel_consumed, avg_fuel_efficiency, total_trips, operational_hours, idle_hours, maintenance_hours, created_at FROM vehicle_daily_summary "+(companyId==null?"":"WHERE company_id = ? " )+"ORDER BY summary_date DESC, created_at DESC"; return companyId==null?jdbcTemplate.query(sql,this::mapRow):jdbcTemplate.query(sql,this::mapRow,companyId);} 
public Optional<VehicleDailySummary> findById(UUID id){ return jdbcTemplate.query("SELECT summary_id, company_id, company_code, vehicle_id, summary_date, total_distance, total_engine_hours, total_fuel_consumed, avg_fuel_efficiency, total_trips, operational_hours, idle_hours, maintenance_hours, created_at FROM vehicle_daily_summary WHERE summary_id = ?", this::mapRow, id).stream().findFirst(); }
public VehicleDailySummary create(VehicleDailySummaryUpsertRequest r){ String sql="""
INSERT INTO vehicle_daily_summary (company_id, company_code, vehicle_id, summary_date, total_distance, total_engine_hours, total_fuel_consumed, avg_fuel_efficiency, total_trips, operational_hours, idle_hours, maintenance_hours)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING summary_id, company_id, company_code, vehicle_id, summary_date, total_distance, total_engine_hours, total_fuel_consumed, avg_fuel_efficiency, total_trips, operational_hours, idle_hours, maintenance_hours, created_at
"""; return jdbcTemplate.queryForObject(sql,this::mapRow,r.companyId(),r.companyCode(),r.vehicleId(),r.summaryDate(),r.totalDistance(),r.totalEngineHours(),r.totalFuelConsumed(),r.avgFuelEfficiency(),r.totalTrips(),r.operationalHours(),r.idleHours(),r.maintenanceHours()); }
public Optional<VehicleDailySummary> update(UUID id,VehicleDailySummaryUpsertRequest r){ String sql="""
UPDATE vehicle_daily_summary SET company_id = COALESCE(?, company_id), company_code = COALESCE(?, company_code), vehicle_id = COALESCE(?, vehicle_id), summary_date = COALESCE(?, summary_date), total_distance = COALESCE(?, total_distance), total_engine_hours = COALESCE(?, total_engine_hours), total_fuel_consumed = COALESCE(?, total_fuel_consumed), avg_fuel_efficiency = COALESCE(?, avg_fuel_efficiency), total_trips = COALESCE(?, total_trips), operational_hours = COALESCE(?, operational_hours), idle_hours = COALESCE(?, idle_hours), maintenance_hours = COALESCE(?, maintenance_hours)
WHERE summary_id = ?
RETURNING summary_id, company_id, company_code, vehicle_id, summary_date, total_distance, total_engine_hours, total_fuel_consumed, avg_fuel_efficiency, total_trips, operational_hours, idle_hours, maintenance_hours, created_at
"""; return jdbcTemplate.query(sql,this::mapRow,r.companyId(),r.companyCode(),r.vehicleId(),r.summaryDate(),r.totalDistance(),r.totalEngineHours(),r.totalFuelConsumed(),r.avgFuelEfficiency(),r.totalTrips(),r.operationalHours(),r.idleHours(),r.maintenanceHours(),id).stream().findFirst(); }
public boolean delete(UUID id){ return jdbcTemplate.update("DELETE FROM vehicle_daily_summary WHERE summary_id = ?", id)>0; }
private VehicleDailySummary mapRow(ResultSet rs,int n)throws SQLException{ java.sql.Date summaryDateDate=rs.getDate("summary_date"); Timestamp createdAtTs=rs.getTimestamp("created_at"); return new VehicleDailySummary(rs.getObject("summary_id",UUID.class),rs.getObject("company_id",UUID.class),rs.getString("company_code"),rs.getObject("vehicle_id",UUID.class),summaryDateDate==null?null:summaryDateDate.toLocalDate(),rs.getBigDecimal("total_distance"),rs.getBigDecimal("total_engine_hours"),rs.getBigDecimal("total_fuel_consumed"),rs.getBigDecimal("avg_fuel_efficiency"),rs.getObject("total_trips",Integer.class),rs.getBigDecimal("operational_hours"),rs.getBigDecimal("idle_hours"),rs.getBigDecimal("maintenance_hours"),createdAtTs==null?null:createdAtTs.toInstant()); }
}
