package genxsolution.vms.vmsbackend.vehicle_management.vehicle_assignment.repository;
import genxsolution.vms.vmsbackend.vehicle_management.vehicle_assignment.dto.VehicleAssignmentUpsertRequest; import genxsolution.vms.vmsbackend.vehicle_management.vehicle_assignment.model.VehicleAssignment; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Repository; import java.sql.*; import java.util.*;
@Repository public class VehicleAssignmentRepository { private final JdbcTemplate jdbcTemplate; public VehicleAssignmentRepository(JdbcTemplate jdbcTemplate){this.jdbcTemplate=jdbcTemplate;}
public List<VehicleAssignment> findAll(UUID companyId){ String sql="SELECT assignment_id, company_id, company_code, vehicle_id, assignment_type_id, assigned_to_employee_id, assigned_to_project_id, assigned_at, expected_return_at, returned_at, start_odometer_km, end_odometer_km, start_fuel_level_percent, end_fuel_level_percent, status_id, created_at FROM vehicle_assignment "+(companyId==null?"":"WHERE company_id = ? " )+"ORDER BY assigned_at DESC, created_at DESC"; return companyId==null?jdbcTemplate.query(sql,this::mapRow):jdbcTemplate.query(sql,this::mapRow,companyId);} 
public Optional<VehicleAssignment> findById(UUID id){ return jdbcTemplate.query("SELECT assignment_id, company_id, company_code, vehicle_id, assignment_type_id, assigned_to_employee_id, assigned_to_project_id, assigned_at, expected_return_at, returned_at, start_odometer_km, end_odometer_km, start_fuel_level_percent, end_fuel_level_percent, status_id, created_at FROM vehicle_assignment WHERE assignment_id = ?", this::mapRow, id).stream().findFirst(); }
public VehicleAssignment create(VehicleAssignmentUpsertRequest r){ String sql="""
INSERT INTO vehicle_assignment (company_id, company_code, vehicle_id, assignment_type_id, assigned_to_employee_id, assigned_to_project_id, assigned_at, expected_return_at, returned_at, start_odometer_km, end_odometer_km, start_fuel_level_percent, end_fuel_level_percent, status_id)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING assignment_id, company_id, company_code, vehicle_id, assignment_type_id, assigned_to_employee_id, assigned_to_project_id, assigned_at, expected_return_at, returned_at, start_odometer_km, end_odometer_km, start_fuel_level_percent, end_fuel_level_percent, status_id, created_at
"""; return jdbcTemplate.queryForObject(sql,this::mapRow,r.companyId(),r.companyCode(),r.vehicleId(),r.assignmentTypeId(),r.assignedToEmployeeId(),r.assignedToProjectId(),r.assignedAt(),r.expectedReturnAt(),r.returnedAt(),r.startOdometerKm(),r.endOdometerKm(),r.startFuelLevelPercent(),r.endFuelLevelPercent(),r.statusId()); }
public Optional<VehicleAssignment> update(UUID id,VehicleAssignmentUpsertRequest r){ String sql="""
UPDATE vehicle_assignment SET vehicle_id = COALESCE(?, vehicle_id), assignment_type_id = COALESCE(?, assignment_type_id), assigned_to_employee_id = COALESCE(?, assigned_to_employee_id), assigned_to_project_id = COALESCE(?, assigned_to_project_id), assigned_at = COALESCE(?, assigned_at), expected_return_at = COALESCE(?, expected_return_at), returned_at = COALESCE(?, returned_at), start_odometer_km = COALESCE(?, start_odometer_km), end_odometer_km = COALESCE(?, end_odometer_km), start_fuel_level_percent = COALESCE(?, start_fuel_level_percent), end_fuel_level_percent = COALESCE(?, end_fuel_level_percent), status_id = COALESCE(?, status_id)
WHERE assignment_id = ?
RETURNING assignment_id, company_id, company_code, vehicle_id, assignment_type_id, assigned_to_employee_id, assigned_to_project_id, assigned_at, expected_return_at, returned_at, start_odometer_km, end_odometer_km, start_fuel_level_percent, end_fuel_level_percent, status_id, created_at
"""; return jdbcTemplate.query(sql,this::mapRow,r.vehicleId(),r.assignmentTypeId(),r.assignedToEmployeeId(),r.assignedToProjectId(),r.assignedAt(),r.expectedReturnAt(),r.returnedAt(),r.startOdometerKm(),r.endOdometerKm(),r.startFuelLevelPercent(),r.endFuelLevelPercent(),r.statusId(),id).stream().findFirst(); }
public boolean delete(UUID id){ return jdbcTemplate.update("DELETE FROM vehicle_assignment WHERE assignment_id = ?", id)>0; }
private VehicleAssignment mapRow(ResultSet rs,int n)throws SQLException{ Timestamp assignedAtTs=rs.getTimestamp("assigned_at"); Timestamp expectedReturnAtTs=rs.getTimestamp("expected_return_at"); Timestamp returnedAtTs=rs.getTimestamp("returned_at"); Timestamp createdAtTs=rs.getTimestamp("created_at"); return new VehicleAssignment(rs.getObject("assignment_id",UUID.class),rs.getObject("company_id",UUID.class),rs.getString("company_code"),rs.getObject("vehicle_id",UUID.class),rs.getObject("assignment_type_id",Integer.class),rs.getObject("assigned_to_employee_id",UUID.class),rs.getObject("assigned_to_project_id",UUID.class),assignedAtTs==null?null:assignedAtTs.toInstant(),expectedReturnAtTs==null?null:expectedReturnAtTs.toInstant(),returnedAtTs==null?null:returnedAtTs.toInstant(),rs.getBigDecimal("start_odometer_km"),rs.getBigDecimal("end_odometer_km"),rs.getBigDecimal("start_fuel_level_percent"),rs.getBigDecimal("end_fuel_level_percent"),rs.getObject("status_id",Integer.class),createdAtTs==null?null:createdAtTs.toInstant()); }
}
