package genxsolution.vms.vmsbackend.vehicle_management.vehicle_running_log.repository;
import genxsolution.vms.vmsbackend.vehicle_management.vehicle_running_log.dto.VehicleRunningLogUpsertRequest; import genxsolution.vms.vmsbackend.vehicle_management.vehicle_running_log.model.VehicleRunningLog; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Repository; import java.sql.*; import java.util.*;
@Repository public class VehicleRunningLogRepository { private final JdbcTemplate jdbcTemplate; public VehicleRunningLogRepository(JdbcTemplate jdbcTemplate){this.jdbcTemplate=jdbcTemplate;}
public List<VehicleRunningLog> findAll(UUID companyId){ String sql="SELECT log_id, company_id, company_code, vehicle_id, driver_id, project_id, log_date, start_time, end_time, start_odometer, end_odometer, total_distance, engine_hours, fuel_consumed, work_type_id, work_description, load_capacity_used, trips_count, operator_signature, supervisor_approval, created_at FROM vehicle_running_log "+(companyId==null?"":"WHERE company_id = ? " )+"ORDER BY log_date DESC, created_at DESC"; return companyId==null?jdbcTemplate.query(sql,this::mapRow):jdbcTemplate.query(sql,this::mapRow,companyId);} 
public Optional<VehicleRunningLog> findById(UUID id){ return jdbcTemplate.query("SELECT log_id, company_id, company_code, vehicle_id, driver_id, project_id, log_date, start_time, end_time, start_odometer, end_odometer, total_distance, engine_hours, fuel_consumed, work_type_id, work_description, load_capacity_used, trips_count, operator_signature, supervisor_approval, created_at FROM vehicle_running_log WHERE log_id = ?", this::mapRow, id).stream().findFirst(); }
public VehicleRunningLog create(VehicleRunningLogUpsertRequest r){ String sql="""
INSERT INTO vehicle_running_log (company_id, company_code, vehicle_id, driver_id, project_id, log_date, start_time, end_time, start_odometer, end_odometer, total_distance, engine_hours, fuel_consumed, work_type_id, work_description, load_capacity_used, trips_count, operator_signature, supervisor_approval)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING log_id, company_id, company_code, vehicle_id, driver_id, project_id, log_date, start_time, end_time, start_odometer, end_odometer, total_distance, engine_hours, fuel_consumed, work_type_id, work_description, load_capacity_used, trips_count, operator_signature, supervisor_approval, created_at
"""; return jdbcTemplate.queryForObject(sql,this::mapRow,r.companyId(),r.companyCode(),r.vehicleId(),r.driverId(),r.projectId(),r.logDate(),r.startTime(),r.endTime(),r.startOdometer(),r.endOdometer(),r.totalDistance(),r.engineHours(),r.fuelConsumed(),r.workTypeId(),r.workDescription(),r.loadCapacityUsed(),r.tripsCount(),r.operatorSignature(),r.supervisorApproval()); }
public Optional<VehicleRunningLog> update(UUID id,VehicleRunningLogUpsertRequest r){ String sql="""
UPDATE vehicle_running_log SET company_id = COALESCE(?, company_id), company_code = COALESCE(?, company_code), vehicle_id = COALESCE(?, vehicle_id), driver_id = COALESCE(?, driver_id), project_id = COALESCE(?, project_id), log_date = COALESCE(?, log_date), start_time = COALESCE(?, start_time), end_time = COALESCE(?, end_time), start_odometer = COALESCE(?, start_odometer), end_odometer = COALESCE(?, end_odometer), total_distance = COALESCE(?, total_distance), engine_hours = COALESCE(?, engine_hours), fuel_consumed = COALESCE(?, fuel_consumed), work_type_id = COALESCE(?, work_type_id), work_description = COALESCE(?, work_description), load_capacity_used = COALESCE(?, load_capacity_used), trips_count = COALESCE(?, trips_count), operator_signature = COALESCE(?, operator_signature), supervisor_approval = COALESCE(?, supervisor_approval)
WHERE log_id = ?
RETURNING log_id, company_id, company_code, vehicle_id, driver_id, project_id, log_date, start_time, end_time, start_odometer, end_odometer, total_distance, engine_hours, fuel_consumed, work_type_id, work_description, load_capacity_used, trips_count, operator_signature, supervisor_approval, created_at
"""; return jdbcTemplate.query(sql,this::mapRow,r.companyId(),r.companyCode(),r.vehicleId(),r.driverId(),r.projectId(),r.logDate(),r.startTime(),r.endTime(),r.startOdometer(),r.endOdometer(),r.totalDistance(),r.engineHours(),r.fuelConsumed(),r.workTypeId(),r.workDescription(),r.loadCapacityUsed(),r.tripsCount(),r.operatorSignature(),r.supervisorApproval(),id).stream().findFirst(); }
public boolean delete(UUID id){ return jdbcTemplate.update("DELETE FROM vehicle_running_log WHERE log_id = ?", id)>0; }
private VehicleRunningLog mapRow(ResultSet rs,int n)throws SQLException{ java.sql.Date logDateDate=rs.getDate("log_date"); Timestamp startTimeTs=rs.getTimestamp("start_time"); Timestamp endTimeTs=rs.getTimestamp("end_time"); Timestamp createdAtTs=rs.getTimestamp("created_at"); return new VehicleRunningLog(rs.getObject("log_id",UUID.class),rs.getObject("company_id",UUID.class),rs.getString("company_code"),rs.getObject("vehicle_id",UUID.class),rs.getObject("driver_id",UUID.class),rs.getObject("project_id",UUID.class),logDateDate==null?null:logDateDate.toLocalDate(),startTimeTs==null?null:startTimeTs.toInstant(),endTimeTs==null?null:endTimeTs.toInstant(),rs.getBigDecimal("start_odometer"),rs.getBigDecimal("end_odometer"),rs.getBigDecimal("total_distance"),rs.getBigDecimal("engine_hours"),rs.getBigDecimal("fuel_consumed"),rs.getObject("work_type_id",Integer.class),rs.getString("work_description"),rs.getBigDecimal("load_capacity_used"),rs.getObject("trips_count",Integer.class),rs.getString("operator_signature"),rs.getObject("supervisor_approval",UUID.class),createdAtTs==null?null:createdAtTs.toInstant()); }
}
