package genxsolution.vms.vmsbackend.vehicle_management.vehicle_operating_cost.repository;
import genxsolution.vms.vmsbackend.vehicle_management.vehicle_operating_cost.dto.VehicleOperatingCostUpsertRequest; import genxsolution.vms.vmsbackend.vehicle_management.vehicle_operating_cost.model.VehicleOperatingCost; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Repository; import java.sql.*; import java.util.*;
@Repository public class VehicleOperatingCostRepository { private final JdbcTemplate jdbcTemplate; public VehicleOperatingCostRepository(JdbcTemplate jdbcTemplate){this.jdbcTemplate=jdbcTemplate;}
public List<VehicleOperatingCost> findAll(UUID companyId){ String sql="SELECT cost_id, company_id, company_code, vehicle_id, cost_date, cost_type_id, description, amount, odometer_km, reference_type, reference_id, created_at FROM vehicle_operating_cost "+(companyId==null?"":"WHERE company_id = ? " )+"ORDER BY cost_date DESC, created_at DESC"; return companyId==null?jdbcTemplate.query(sql,this::mapRow):jdbcTemplate.query(sql,this::mapRow,companyId);} 
public Optional<VehicleOperatingCost> findById(UUID id){ return jdbcTemplate.query("SELECT cost_id, company_id, company_code, vehicle_id, cost_date, cost_type_id, description, amount, odometer_km, reference_type, reference_id, created_at FROM vehicle_operating_cost WHERE cost_id = ?", this::mapRow, id).stream().findFirst(); }
public VehicleOperatingCost create(VehicleOperatingCostUpsertRequest r){ String sql="""
INSERT INTO vehicle_operating_cost (company_id, company_code, vehicle_id, cost_date, cost_type_id, description, amount, odometer_km, reference_type, reference_id)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING cost_id, company_id, company_code, vehicle_id, cost_date, cost_type_id, description, amount, odometer_km, reference_type, reference_id, created_at
"""; return jdbcTemplate.queryForObject(sql,this::mapRow,r.companyId(),r.companyCode(),r.vehicleId(),r.costDate(),r.costTypeId(),r.description(),r.amount(),r.odometerKm(),r.referenceType(),r.referenceId()); }
public Optional<VehicleOperatingCost> update(UUID id,VehicleOperatingCostUpsertRequest r){ String sql="""
UPDATE vehicle_operating_cost SET company_id = COALESCE(?, company_id), company_code = COALESCE(?, company_code), vehicle_id = COALESCE(?, vehicle_id), cost_date = COALESCE(?, cost_date), cost_type_id = COALESCE(?, cost_type_id), description = COALESCE(?, description), amount = COALESCE(?, amount), odometer_km = COALESCE(?, odometer_km), reference_type = COALESCE(?, reference_type), reference_id = COALESCE(?, reference_id)
WHERE cost_id = ?
RETURNING cost_id, company_id, company_code, vehicle_id, cost_date, cost_type_id, description, amount, odometer_km, reference_type, reference_id, created_at
"""; return jdbcTemplate.query(sql,this::mapRow,r.companyId(),r.companyCode(),r.vehicleId(),r.costDate(),r.costTypeId(),r.description(),r.amount(),r.odometerKm(),r.referenceType(),r.referenceId(),id).stream().findFirst(); }
public boolean delete(UUID id){ return jdbcTemplate.update("DELETE FROM vehicle_operating_cost WHERE cost_id = ?", id)>0; }
private VehicleOperatingCost mapRow(ResultSet rs,int n)throws SQLException{ java.sql.Date costDateDate=rs.getDate("cost_date"); Timestamp createdAtTs=rs.getTimestamp("created_at"); return new VehicleOperatingCost(rs.getObject("cost_id",UUID.class),rs.getObject("company_id",UUID.class),rs.getString("company_code"),rs.getObject("vehicle_id",UUID.class),costDateDate==null?null:costDateDate.toLocalDate(),rs.getObject("cost_type_id",Integer.class),rs.getString("description"),rs.getBigDecimal("amount"),rs.getBigDecimal("odometer_km"),rs.getString("reference_type"),rs.getObject("reference_id",UUID.class),createdAtTs==null?null:createdAtTs.toInstant()); }
}
