package genxsolution.vms.vmsbackend.maintenance_management.maintenance_schedule.repository;
import genxsolution.vms.vmsbackend.maintenance_management.maintenance_schedule.dto.MaintenanceScheduleUpsertRequest; import genxsolution.vms.vmsbackend.maintenance_management.maintenance_schedule.model.MaintenanceSchedule; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Repository; import java.sql.*; import java.util.*;
@Repository public class MaintenanceScheduleRepository { private final JdbcTemplate jdbcTemplate; public MaintenanceScheduleRepository(JdbcTemplate jdbcTemplate){this.jdbcTemplate=jdbcTemplate;}
public List<MaintenanceSchedule> findAll(UUID companyId){ String sql="SELECT schedule_id, company_id, company_code, vehicle_id, standard_id, scheduled_date, scheduled_odometer_km, scheduled_engine_hours, ai_predicted_date, prediction_confidence, status_id, notification_sent, notification_sent_date, reminder_count, created_at, created_by FROM maintenance_schedule "+(companyId==null?"":"WHERE company_id = ? ")+"ORDER BY created_at DESC"; return companyId==null?jdbcTemplate.query(sql,this::mapRow):jdbcTemplate.query(sql,this::mapRow,companyId); }
public Optional<MaintenanceSchedule> findById(UUID id){ return jdbcTemplate.query("SELECT schedule_id, company_id, company_code, vehicle_id, standard_id, scheduled_date, scheduled_odometer_km, scheduled_engine_hours, ai_predicted_date, prediction_confidence, status_id, notification_sent, notification_sent_date, reminder_count, created_at, created_by FROM maintenance_schedule WHERE schedule_id = ?", this::mapRow, id).stream().findFirst(); }
public MaintenanceSchedule create(MaintenanceScheduleUpsertRequest r){ String sql="""
INSERT INTO maintenance_schedule (company_id, company_code, vehicle_id, standard_id, scheduled_date, scheduled_odometer_km, scheduled_engine_hours, ai_predicted_date, prediction_confidence, status_id, notification_sent, notification_sent_date, reminder_count, created_by)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING schedule_id, company_id, company_code, vehicle_id, standard_id, scheduled_date, scheduled_odometer_km, scheduled_engine_hours, ai_predicted_date, prediction_confidence, status_id, notification_sent, notification_sent_date, reminder_count, created_at, created_by
"""; return jdbcTemplate.queryForObject(sql,this::mapRow,r.companyId(),r.companyCode(),r.vehicleId(),r.standardId(),r.scheduledDate(),r.scheduledOdometerKm(),r.scheduledEngineHours(),r.aiPredictedDate(),r.predictionConfidence(),r.statusId(),r.notificationSent(),r.notificationSentDate(),r.reminderCount(),r.createdBy()); }
public Optional<MaintenanceSchedule> update(UUID id,MaintenanceScheduleUpsertRequest r){ String sql="""
UPDATE maintenance_schedule SET company_id = COALESCE(?, company_id), company_code = COALESCE(?, company_code), vehicle_id = COALESCE(?, vehicle_id), standard_id = COALESCE(?, standard_id), scheduled_date = COALESCE(?, scheduled_date), scheduled_odometer_km = COALESCE(?, scheduled_odometer_km), scheduled_engine_hours = COALESCE(?, scheduled_engine_hours), ai_predicted_date = COALESCE(?, ai_predicted_date), prediction_confidence = COALESCE(?, prediction_confidence), status_id = COALESCE(?, status_id), notification_sent = COALESCE(?, notification_sent), notification_sent_date = COALESCE(?, notification_sent_date), reminder_count = COALESCE(?, reminder_count), created_by = COALESCE(?, created_by)
WHERE schedule_id = ?
RETURNING schedule_id, company_id, company_code, vehicle_id, standard_id, scheduled_date, scheduled_odometer_km, scheduled_engine_hours, ai_predicted_date, prediction_confidence, status_id, notification_sent, notification_sent_date, reminder_count, created_at, created_by
"""; return jdbcTemplate.query(sql,this::mapRow,r.companyId(),r.companyCode(),r.vehicleId(),r.standardId(),r.scheduledDate(),r.scheduledOdometerKm(),r.scheduledEngineHours(),r.aiPredictedDate(),r.predictionConfidence(),r.statusId(),r.notificationSent(),r.notificationSentDate(),r.reminderCount(),r.createdBy(),id).stream().findFirst(); }
public boolean delete(UUID id){ return jdbcTemplate.update("DELETE FROM maintenance_schedule WHERE schedule_id = ?", id)>0; }
private MaintenanceSchedule mapRow(ResultSet rs,int n)throws SQLException{ java.sql.Date scheduledDateDate=rs.getDate("scheduled_date"); java.sql.Date aiPredictedDateDate=rs.getDate("ai_predicted_date"); Timestamp notificationSentDateTs=rs.getTimestamp("notification_sent_date"); Timestamp createdAtTs=rs.getTimestamp("created_at"); return new MaintenanceSchedule(rs.getObject("schedule_id",UUID.class),rs.getObject("company_id",UUID.class),rs.getString("company_code"),rs.getObject("vehicle_id",UUID.class),rs.getObject("standard_id",UUID.class),scheduledDateDate==null?null:scheduledDateDate.toLocalDate(),rs.getBigDecimal("scheduled_odometer_km"),rs.getBigDecimal("scheduled_engine_hours"),aiPredictedDateDate==null?null:aiPredictedDateDate.toLocalDate(),rs.getBigDecimal("prediction_confidence"),rs.getObject("status_id",Integer.class),rs.getObject("notification_sent",Boolean.class),notificationSentDateTs==null?null:notificationSentDateTs.toInstant(),rs.getObject("reminder_count",Integer.class),createdAtTs==null?null:createdAtTs.toInstant(),rs.getObject("created_by",UUID.class)); }
}
