ALTER TABLE vehicle
    ADD COLUMN IF NOT EXISTS registered_year INTEGER;

ALTER TABLE vehicle
    ADD COLUMN IF NOT EXISTS country VARCHAR(100);

ALTER TABLE vehicle
    ADD COLUMN IF NOT EXISTS air_condition BOOLEAN DEFAULT FALSE;
