package genxsolution.vms.vmsbackend.vehicle_management.vehicle_daily_activity.repository;
import genxsolution.vms.vmsbackend.vehicle_management.vehicle_daily_activity.dto.VehicleDailyActivityUpsertRequest; import genxsolution.vms.vmsbackend.vehicle_management.vehicle_daily_activity.model.VehicleDailyActivity; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Repository; import java.sql.*; import java.util.*;
@Repository public class VehicleDailyActivityRepository { private final JdbcTemplate jdbcTemplate; public VehicleDailyActivityRepository(JdbcTemplate jdbcTemplate){this.jdbcTemplate=jdbcTemplate;}
public List<VehicleDailyActivity> findAll(UUID companyId){ String sql="SELECT activity_id, company_id, company_code, vehicle_id, driver_id, project_id, activity_date, start_time, end_time, start_odometer_km, end_odometer_km, engine_hours, distance_km, work_description, remarks, created_at FROM vehicle_daily_activity "+(companyId==null?"":"WHERE company_id = ? " )+"ORDER BY activity_date DESC, created_at DESC"; return companyId==null?jdbcTemplate.query(sql,this::mapRow):jdbcTemplate.query(sql,this::mapRow,companyId);} 
public Optional<VehicleDailyActivity> findById(UUID id){ return jdbcTemplate.query("SELECT activity_id, company_id, company_code, vehicle_id, driver_id, project_id, activity_date, start_time, end_time, start_odometer_km, end_odometer_km, engine_hours, distance_km, work_description, remarks, created_at FROM vehicle_daily_activity WHERE activity_id = ?", this::mapRow, id).stream().findFirst(); }
public VehicleDailyActivity create(VehicleDailyActivityUpsertRequest r){ String sql="""
INSERT INTO vehicle_daily_activity (company_id, company_code, vehicle_id, driver_id, project_id, activity_date, start_time, end_time, start_odometer_km, end_odometer_km, engine_hours, distance_km, work_description, remarks)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING activity_id, company_id, company_code, vehicle_id, driver_id, project_id, activity_date, start_time, end_time, start_odometer_km, end_odometer_km, engine_hours, distance_km, work_description, remarks, created_at
"""; return jdbcTemplate.queryForObject(sql,this::mapRow,r.companyId(),r.companyCode(),r.vehicleId(),r.driverId(),r.projectId(),r.activityDate(),r.startTime(),r.endTime(),r.startOdometerKm(),r.endOdometerKm(),r.engineHours(),r.distanceKm(),r.workDescription(),r.remarks()); }
public Optional<VehicleDailyActivity> update(UUID id,VehicleDailyActivityUpsertRequest r){ String sql="""
UPDATE vehicle_daily_activity SET company_id = COALESCE(?, company_id), company_code = COALESCE(?, company_code), vehicle_id = COALESCE(?, vehicle_id), driver_id = COALESCE(?, driver_id), project_id = COALESCE(?, project_id), activity_date = COALESCE(?, activity_date), start_time = COALESCE(?, start_time), end_time = COALESCE(?, end_time), start_odometer_km = COALESCE(?, start_odometer_km), end_odometer_km = COALESCE(?, end_odometer_km), engine_hours = COALESCE(?, engine_hours), distance_km = COALESCE(?, distance_km), work_description = COALESCE(?, work_description), remarks = COALESCE(?, remarks)
WHERE activity_id = ?
RETURNING activity_id, company_id, company_code, vehicle_id, driver_id, project_id, activity_date, start_time, end_time, start_odometer_km, end_odometer_km, engine_hours, distance_km, work_description, remarks, created_at
"""; return jdbcTemplate.query(sql,this::mapRow,r.companyId(),r.companyCode(),r.vehicleId(),r.driverId(),r.projectId(),r.activityDate(),r.startTime(),r.endTime(),r.startOdometerKm(),r.endOdometerKm(),r.engineHours(),r.distanceKm(),r.workDescription(),r.remarks(),id).stream().findFirst(); }
public boolean delete(UUID id){ return jdbcTemplate.update("DELETE FROM vehicle_daily_activity WHERE activity_id = ?", id)>0; }
private VehicleDailyActivity mapRow(ResultSet rs,int n)throws SQLException{ java.sql.Date activityDateDate=rs.getDate("activity_date"); Timestamp startTimeTs=rs.getTimestamp("start_time"); Timestamp endTimeTs=rs.getTimestamp("end_time"); Timestamp createdAtTs=rs.getTimestamp("created_at"); return new VehicleDailyActivity(rs.getObject("activity_id",UUID.class),rs.getObject("company_id",UUID.class),rs.getString("company_code"),rs.getObject("vehicle_id",UUID.class),rs.getObject("driver_id",UUID.class),rs.getObject("project_id",UUID.class),activityDateDate==null?null:activityDateDate.toLocalDate(),startTimeTs==null?null:startTimeTs.toInstant(),endTimeTs==null?null:endTimeTs.toInstant(),rs.getBigDecimal("start_odometer_km"),rs.getBigDecimal("end_odometer_km"),rs.getBigDecimal("engine_hours"),rs.getBigDecimal("distance_km"),rs.getString("work_description"),rs.getString("remarks"),createdAtTs==null?null:createdAtTs.toInstant()); }
}
