package genxsolution.vms.vmsbackend.maintenance_management.vehicle_maintenance_program_assignment.repository;
import genxsolution.vms.vmsbackend.maintenance_management.vehicle_maintenance_program_assignment.dto.VehicleMaintenanceProgramAssignmentUpsertRequest; import genxsolution.vms.vmsbackend.maintenance_management.vehicle_maintenance_program_assignment.model.VehicleMaintenanceProgramAssignment; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Repository; import java.sql.*; import java.util.*;
@Repository public class VehicleMaintenanceProgramAssignmentRepository { private final JdbcTemplate jdbcTemplate; public VehicleMaintenanceProgramAssignmentRepository(JdbcTemplate jdbcTemplate){this.jdbcTemplate=jdbcTemplate;}
public List<VehicleMaintenanceProgramAssignment> findAll(UUID companyId){ String sql="SELECT assignment_id, company_id, company_code, vehicle_id, template_id, start_date, end_date, current_odometer, current_engine_hours, next_service_date, next_service_odometer, next_service_hours, is_active, created_at FROM vehicle_maintenance_program_assignment "+(companyId==null?"":"WHERE company_id = ? ")+"ORDER BY created_at DESC"; return companyId==null?jdbcTemplate.query(sql,this::mapRow):jdbcTemplate.query(sql,this::mapRow,companyId); }
public Optional<VehicleMaintenanceProgramAssignment> findById(UUID id){ return jdbcTemplate.query("SELECT assignment_id, company_id, company_code, vehicle_id, template_id, start_date, end_date, current_odometer, current_engine_hours, next_service_date, next_service_odometer, next_service_hours, is_active, created_at FROM vehicle_maintenance_program_assignment WHERE assignment_id = ?", this::mapRow, id).stream().findFirst(); }
public VehicleMaintenanceProgramAssignment create(VehicleMaintenanceProgramAssignmentUpsertRequest r){ String sql="""
INSERT INTO vehicle_maintenance_program_assignment (company_id, company_code, vehicle_id, template_id, start_date, end_date, current_odometer, current_engine_hours, next_service_date, next_service_odometer, next_service_hours, is_active)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING assignment_id, company_id, company_code, vehicle_id, template_id, start_date, end_date, current_odometer, current_engine_hours, next_service_date, next_service_odometer, next_service_hours, is_active, created_at
"""; return jdbcTemplate.queryForObject(sql,this::mapRow,r.companyId(),r.companyCode(),r.vehicleId(),r.templateId(),r.startDate(),r.endDate(),r.currentOdometer(),r.currentEngineHours(),r.nextServiceDate(),r.nextServiceOdometer(),r.nextServiceHours(),r.isActive()); }
public Optional<VehicleMaintenanceProgramAssignment> update(UUID id,VehicleMaintenanceProgramAssignmentUpsertRequest r){ String sql="""
UPDATE vehicle_maintenance_program_assignment SET company_id = COALESCE(?, company_id), company_code = COALESCE(?, company_code), vehicle_id = COALESCE(?, vehicle_id), template_id = COALESCE(?, template_id), start_date = COALESCE(?, start_date), end_date = COALESCE(?, end_date), current_odometer = COALESCE(?, current_odometer), current_engine_hours = COALESCE(?, current_engine_hours), next_service_date = COALESCE(?, next_service_date), next_service_odometer = COALESCE(?, next_service_odometer), next_service_hours = COALESCE(?, next_service_hours), is_active = COALESCE(?, is_active)
WHERE assignment_id = ?
RETURNING assignment_id, company_id, company_code, vehicle_id, template_id, start_date, end_date, current_odometer, current_engine_hours, next_service_date, next_service_odometer, next_service_hours, is_active, created_at
"""; return jdbcTemplate.query(sql,this::mapRow,r.companyId(),r.companyCode(),r.vehicleId(),r.templateId(),r.startDate(),r.endDate(),r.currentOdometer(),r.currentEngineHours(),r.nextServiceDate(),r.nextServiceOdometer(),r.nextServiceHours(),r.isActive(),id).stream().findFirst(); }
public boolean delete(UUID id){ return jdbcTemplate.update("DELETE FROM vehicle_maintenance_program_assignment WHERE assignment_id = ?", id)>0; }
private VehicleMaintenanceProgramAssignment mapRow(ResultSet rs,int n)throws SQLException{ java.sql.Date startDateDate=rs.getDate("start_date"); java.sql.Date endDateDate=rs.getDate("end_date"); java.sql.Date nextServiceDateDate=rs.getDate("next_service_date"); Timestamp createdAtTs=rs.getTimestamp("created_at"); return new VehicleMaintenanceProgramAssignment(rs.getObject("assignment_id",UUID.class),rs.getObject("company_id",UUID.class),rs.getString("company_code"),rs.getObject("vehicle_id",UUID.class),rs.getObject("template_id",UUID.class),startDateDate==null?null:startDateDate.toLocalDate(),endDateDate==null?null:endDateDate.toLocalDate(),rs.getBigDecimal("current_odometer"),rs.getBigDecimal("current_engine_hours"),nextServiceDateDate==null?null:nextServiceDateDate.toLocalDate(),rs.getBigDecimal("next_service_odometer"),rs.getBigDecimal("next_service_hours"),rs.getObject("is_active",Boolean.class),createdAtTs==null?null:createdAtTs.toInstant()); }
}
